version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: project_postgres
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 260903
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 260903
      DB_NAME: attendance_db
      DB_SSLMODE: disable
      PORT: 8080
      GIN_MODE: release
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - project_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network:
    driver: bridge
